version: "3"

services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    container_name: dev-container
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - foundryvtt
  foundryvtt:
    # Other Versions:
    # image: felddy/foundryvtt:13.344.0
    # image: felddy/foundryvtt:12.331.0
    image: felddy/foundryvtt:13.344.0
    container_name: foundryvtt
    environment:
      - FOUNDRY_RELEASE_URL=<Get a timed URL from foundryvtt>
      - FOUNDRY_ADMIN_KEY=admin
    ports:
      - "30000:30000"
    user: root
    restart: unless-stopped
    volumes:
      - ..:/data/Data/systems/paranoia
      - /data/Data/systems/paranoia/.git
      - foundryvtt-server:/home/foundry
      - foundryvtt-data:/data

volumes:
  foundryvtt-server:
  foundryvtt-data:
