version: "3"

services:
  dev-container:
    image: mcr.microsoft.com/devcontainers/javascript-node:1-22-bookworm
    container_name: dev-container
    volumes:
      - ..:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    depends_on:
      - foundryvtt
  foundryvtt:
    image: felddy/foundryvtt:12.331.0
    container_name: foundryvtt
    environment:
      - FOUNDRY_RELEASE_URL=https://r2.foundryvtt.com/releases/12.331/FoundryVTT-12.331.zip?verify=1732489634-RGNAqpYuJBA38g6KBAZlXCkAc1cr5W5P%2FBuzngKzjKc%3D
      - FOUNDRY_ADMIN_KEY=admin
    ports:
      - "30000:30000"
    restart: unless-stopped
    volumes:
      - ..:/data/Data/systems/paranoia
      - /data/Data/systems/paranoia/.git
      - foundryvtt-server:/home/foundry
      - foundryvtt-data:/data

volumes:
  foundryvtt-server:
  foundryvtt-data: